### ISSUE TITLE
Rounding error in display of power station

### ISSUE THREAD

**Issue by habi** [openinframap/styles#34]
A small power station close to where I live with 570 kW (https://www.openstreetmap.org/way/284398460) is rendered with 0.57000000001 MW (https://openinframap.org/#17.9/46.946293/7.456445, also see screenshot [1]).

I think there's a rounding error somewhere :)

![screen shot 2018-11-13 at 23 19 51](https://user-images.githubusercontent.com/1651235/48446920-e3586100-e79a-11e8-8e8c-0f8edaaa7805.PNG)

[1]: give or take some zeroes...

**Comment by russss** [comment]
Before I forget where I got to with this issue:

It *appears* that for some floats there is somehow a 1-bit error in the MVT protobuf encoding which causes the number to be slightly wrong when decoded in the browser. It's unclear if this error is with Tegola or the protobuf encoder, or something else.

I can't just fix this by rounding the number in the browser because Mapbox GL doesn't support rounding to arbitrary decimal places.

The saga continues.

**Comment by habi** [comment]
Thanks for investigating!

**Comment by pyrog** [comment]
Another example: [way/62850607](https://www.openstreetmap.org/way/62850607)

[<img width="498" alt="Capture d’écran 2019-03-19 à 16 53 05" src="https://user-images.githubusercontent.com/2158081/54621276-ccd35680-4a67-11e9-8c26-63d4da12f2af.png">](https://openinframap.org/#17.53/45.907194/6.068138)

key|value
-- | --
building | yes
name|Centrale électrique de Brassilly
operator|EDF
plant:output:electricity|2884 kW
power|plant

💡
* Do the rounding in SQL before the tiles generation?
* Or do it in Javascript dynamically when the tiles are loaded (if it's possible)?

**Comment by russss** [comment]
I've fixed this, finally. It was unpleasant.

**Comment by habi** [comment]
Cool, thanks a bunch!
