### ISSUE TITLE
Power plant icons disappear for ≤100MW plants

### ISSUE THREAD

**Issue by Gazer75** [openinframap/styles#36]
Seems they do not display icon at all, but if you zoom out between z11 and 10 they show up for a second before disappearing again.

**Comment by russss** [comment]
`15:07 <russss> the power plant symbol thing is related to the zoom level I show the power plant areas at. The problem is that offshore wind farms are massive and deserve to be shown at a lower zoom, but that logic also applies to tiny power plants which then get their symbol suppressed.`

I've somewhat fixed this by tweaking zoom levels a bit, but the real fix is probably going to be making the rendering level dependent on area size.
